# Generated by Django 4.2.7 on 2023-12-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[(1, 'available'), (0, 'booked')], max_length=1),
        ),
    ]
